### ISSUE TITLE
Are proofs by induction possible?

### ISSUE THREAD

**Issue by umnikos** [nomeata/incredible#127]
I've been trying to create a custom induction block that looks something like this:
```
∀f.f(Z)→((∀x.f(x)→f(s(x)))→(∀x.f(x)))
```
The problem is that, as far as I know, `f` is not actually a function, so I can't use this block on anything like `g(t(x),p(x))` by lambda abstracting it to `f`.

Is there actually a way to do induction somehow or is this a feature that needs to be implemented?

**Comment by nomeata** [comment]
When you say custom induction blook, do you mean within the UI? Or by editing the logics definitions in https://github.com/nomeata/incredible/tree/master/logics?

**Comment by umnikos** [comment]
From the UI by adding an extra proposition to a level. I don't know how the logics folder differs from that

**Comment by nomeata** [comment]
It allows you to define blocks, including interestingly shaped blocks, like this for the block for the ∃ quantifier:
```
- id: exE
  desc:
    elim: ∃
  free: ["P","Q"]
  local: ["c"]
  ports:
    in1:
      type: assumption
      proposition: ∃x.P(x)
    in2:
      type: assumption
      proposition: Q
      scoped: ["c"]
    hyp:
      type: local hypothesis
      proposition: P(c)
      consumedBy: in2
    out:
      type: conclusion
      proposition: Q
```
Maybe it would work, but to be honest, I can’t wrap my head arount it on the spot :-)
